name: Deploy pipeline

on:
  push:
    branches:
      - "github-actions"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkuot last version
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies 
        run: npm install --no-audit --no-fund --no-optinal
        
      - name: list files1
        run: ls -l

      - name: Remove previous dist dir for secutiry
        run: rm -r dir

      - name: list files2
        run: ls -l

      - name: Build proyect
        run: npm run 
        
      - name: list files3
        run: ls -l

